repos:
  - repo: https://github.com/psf/black
    rev: e87737140f32d3cd7c44ede75f02dcd58e55820e  # frozen: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: c4a0b883114b00d8d76b479c820ce7950211c99b  # frozen: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 10f4af6dbcf93456ba7df762278ae61ba3120dc6  # frozen: 6.1.0
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/asottile/reorder-python-imports
    rev: ae11ccbd838e90f7e2a16abbed9276e6a41cafbb  # frozen: v3.12.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/codespell-project/codespell
    rev: 6e41aba91fb32e9feb741a6258eefeb9c6e4a482  # frozen: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: b3b011d5946147b3a58fe2ce49fe200b68e8a1a8  # frozen: v1.6.0
    hooks:
      - id: mypy
