repos:
  - repo: https://github.com/psf/black
    rev: e877371
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7ef0350
    hooks:
      - id: flake8
        language_version: python3

  - repo: https://github.com/asottile/reorder-python-imports
    rev: ba4e0d3
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/codespell-project/codespell
    rev: 355e50e
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 08cbc46
    hooks:
      - id: mypy
